/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as ethioCoinSol from './EthioCoin.sol';
export type { ethioCoinSol };
import type * as jobPayingSystemSol from './JobPayingSystem.sol';
export type { jobPayingSystemSol };
import type * as reputationTokenSol from './ReputationToken.sol';
export type { reputationTokenSol };
import type * as rewardVaultSol from './RewardVault.sol';
export type { rewardVaultSol };
import type * as treasureSol from './Treasure.sol';
export type { treasureSol };
import type * as verifierSystemSol from './VerifierSystem.sol';
export type { verifierSystemSol };
export * as factories from './factories';
export type { EthioCoin } from './EthioCoin.sol/EthioCoin';
export { EthioCoin__factory } from './factories/EthioCoin.sol/EthioCoin__factory';
export type { JobPayingSystem } from './JobPayingSystem.sol/JobPayingSystem';
export { JobPayingSystem__factory } from './factories/JobPayingSystem.sol/JobPayingSystem__factory';
export type { ReputationToken } from './ReputationToken.sol/ReputationToken';
export { ReputationToken__factory } from './factories/ReputationToken.sol/ReputationToken__factory';
export type { RewardVault } from './RewardVault.sol/RewardVault';
export { RewardVault__factory } from './factories/RewardVault.sol/RewardVault__factory';
export type { Treasure } from './Treasure.sol/Treasure';
export { Treasure__factory } from './factories/Treasure.sol/Treasure__factory';
export type { Itreasury } from './VerifierSystem.sol/Itreasury';
export { Itreasury__factory } from './factories/VerifierSystem.sol/Itreasury__factory';
export type { VerifierSystem } from './VerifierSystem.sol/VerifierSystem';
export { VerifierSystem__factory } from './factories/VerifierSystem.sol/VerifierSystem__factory';