/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IVRFV2WrapperInterface extends Interface {
    getFunction(nameOrSignature: "calculateRequestPrice" | "calculateRequestPriceNative"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'calculateRequestPrice', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'calculateRequestPriceNative', values: [BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'calculateRequestPrice', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'calculateRequestPriceNative', data: BytesLike): Result;
  }

  

  export interface IVRFV2Wrapper extends BaseContract {
    
    connect(runner?: ContractRunner | null): IVRFV2Wrapper;
    waitForDeployment(): Promise<this>;

    interface: IVRFV2WrapperInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    calculateRequestPrice: TypedContractMethod<
      [_callbackGasLimit: BigNumberish, _numWords: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    calculateRequestPriceNative: TypedContractMethod<
      [_callbackGasLimit: BigNumberish, _numWords: BigNumberish, ],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'calculateRequestPrice'): TypedContractMethod<
      [_callbackGasLimit: BigNumberish, _numWords: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'calculateRequestPriceNative'): TypedContractMethod<
      [_callbackGasLimit: BigNumberish, _numWords: BigNumberish, ],
      [bigint],
      'view'
    >;

    

    filters: {
      
    };
  }