/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace JobPayingSystem {
      
    export type W_levelStruct = {min_verifiers_portion: BigNumberish, freelancer_stake: BigNumberish, client_stake: BigNumberish, max_amount: BigNumberish, payment_duration: BigNumberish}

    export type W_levelStructOutput = [min_verifiers_portion: bigint, freelancer_stake: bigint, client_stake: bigint, max_amount: bigint, payment_duration: bigint] & {min_verifiers_portion: bigint, freelancer_stake: bigint, client_stake: bigint, max_amount: bigint, payment_duration: bigint }
  

    export type JobStruct = {client: AddressLike, freelancer: AddressLike, freelancer_approved: boolean, freelancer_completed: boolean, appeal_time: BigNumberish, status: BigNumberish, amount: BigNumberish, max_duration: BigNumberish, expiry_timestamp: BigNumberish, level: BigNumberish, cat: BigNumberish}

    export type JobStructOutput = [client: string, freelancer: string, freelancer_approved: boolean, freelancer_completed: boolean, appeal_time: bigint, status: bigint, amount: bigint, max_duration: bigint, expiry_timestamp: bigint, level: bigint, cat: bigint] & {client: string, freelancer: string, freelancer_approved: boolean, freelancer_completed: boolean, appeal_time: bigint, status: bigint, amount: bigint, max_duration: bigint, expiry_timestamp: bigint, level: bigint, cat: bigint }
  
    }

  export interface JobPayingSystemInterface extends Interface {
    getFunction(nameOrSignature: "MIN_MAX_DURATION" | "STAKE_DECIMAL" | "VERIFIERS_RECYCLING_PER_JOB" | "VERIFIER_DECIMAL" | "accept_job" | "append_level" | "authority" | "cancel_hire" | "cancel_job" | "cancel_pending_hire" | "claim_after_dispute" | "client_fee_portion_bps" | "complete_job" | "freelancer_fee_portion_bps" | "freelancers" | "get_job" | "get_job_lists_len" | "get_level" | "get_levels" | "handle_request_payment" | "hire" | "isConsumingScheduledOp" | "job_lists" | "jobs" | "levels_size" | "pay_freelancer" | "post_job" | "raise_dispute" | "refund_after_dispute" | "register_freelancer" | "registry" | "reset_levels" | "setAuthority" | "set_client_fee_portion" | "transfer_freelancer" | "update_level" | "work_levels"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorityUpdated" | "job_accepted" | "job_closed" | "job_completed" | "job_disputed" | "job_hired" | "job_posted" | "transfer_address"): EventFragment;

    encodeFunctionData(functionFragment: 'MIN_MAX_DURATION', values?: undefined): string;
encodeFunctionData(functionFragment: 'STAKE_DECIMAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'VERIFIERS_RECYCLING_PER_JOB', values?: undefined): string;
encodeFunctionData(functionFragment: 'VERIFIER_DECIMAL', values?: undefined): string;
encodeFunctionData(functionFragment: 'accept_job', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'append_level', values: [JobPayingSystem.W_levelStruct]): string;
encodeFunctionData(functionFragment: 'authority', values?: undefined): string;
encodeFunctionData(functionFragment: 'cancel_hire', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cancel_job', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'cancel_pending_hire', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'claim_after_dispute', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'client_fee_portion_bps', values?: undefined): string;
encodeFunctionData(functionFragment: 'complete_job', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'freelancer_fee_portion_bps', values?: undefined): string;
encodeFunctionData(functionFragment: 'freelancers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'get_job', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'get_job_lists_len', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_level', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'get_levels', values?: undefined): string;
encodeFunctionData(functionFragment: 'handle_request_payment', values: [boolean, BigNumberish]): string;
encodeFunctionData(functionFragment: 'hire', values: [BytesLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'isConsumingScheduledOp', values?: undefined): string;
encodeFunctionData(functionFragment: 'job_lists', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'jobs', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'levels_size', values?: undefined): string;
encodeFunctionData(functionFragment: 'pay_freelancer', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'post_job', values: [BytesLike, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'raise_dispute', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'refund_after_dispute', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'register_freelancer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'reset_levels', values: [JobPayingSystem.W_levelStruct[]]): string;
encodeFunctionData(functionFragment: 'setAuthority', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_client_fee_portion', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'transfer_freelancer', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'update_level', values: [JobPayingSystem.W_levelStruct, BigNumberish]): string;
encodeFunctionData(functionFragment: 'work_levels', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'MIN_MAX_DURATION', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'STAKE_DECIMAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VERIFIERS_RECYCLING_PER_JOB', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'VERIFIER_DECIMAL', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'accept_job', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'append_level', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel_hire', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel_job', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancel_pending_hire', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim_after_dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'client_fee_portion_bps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'complete_job', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freelancer_fee_portion_bps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'freelancers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_job', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_job_lists_len', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_level', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_levels', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'handle_request_payment', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hire', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isConsumingScheduledOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'job_lists', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'levels_size', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pay_freelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'post_job', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raise_dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund_after_dispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'register_freelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reset_levels', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_client_fee_portion', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer_freelancer', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'update_level', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'work_levels', data: BytesLike): Result;
  }

  
    export namespace AuthorityUpdatedEvent {
      export type InputTuple = [authority: AddressLike];
      export type OutputTuple = [authority: string];
      export interface OutputObject {authority: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_acceptedEvent {
      export type InputTuple = [job_id: BytesLike, freelancer: AddressLike];
      export type OutputTuple = [job_id: string, freelancer: string];
      export interface OutputObject {job_id: string, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_closedEvent {
      export type InputTuple = [job_id: BytesLike];
      export type OutputTuple = [job_id: string];
      export interface OutputObject {job_id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_completedEvent {
      export type InputTuple = [job_id: BytesLike, freelancer: AddressLike];
      export type OutputTuple = [job_id: string, freelancer: string];
      export interface OutputObject {job_id: string, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_disputedEvent {
      export type InputTuple = [job_id: BytesLike, client: AddressLike, freelancer: AddressLike, stake_burnt: boolean];
      export type OutputTuple = [job_id: string, client: string, freelancer: string, stake_burnt: boolean];
      export interface OutputObject {job_id: string, client: string, freelancer: string, stake_burnt: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_hiredEvent {
      export type InputTuple = [job_id: BytesLike, client: AddressLike, freelancer: AddressLike];
      export type OutputTuple = [job_id: string, client: string, freelancer: string];
      export interface OutputObject {job_id: string, client: string, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_postedEvent {
      export type InputTuple = [job_id: BytesLike];
      export type OutputTuple = [job_id: string];
      export interface OutputObject {job_id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace transfer_addressEvent {
      export type InputTuple = [old_address: AddressLike, new_address: AddressLike];
      export type OutputTuple = [old_address: string, new_address: string];
      export interface OutputObject {old_address: string, new_address: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface JobPayingSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): JobPayingSystem;
    waitForDeployment(): Promise<this>;

    interface: JobPayingSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    MIN_MAX_DURATION: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    STAKE_DECIMAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VERIFIERS_RECYCLING_PER_JOB: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    VERIFIER_DECIMAL: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    accept_job: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    append_level: TypedContractMethod<
      [_level: JobPayingSystem.W_levelStruct, ],
      [void],
      'nonpayable'
    >
    

    
    authority: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    cancel_hire: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancel_job: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    cancel_pending_hire: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    claim_after_dispute: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    client_fee_portion_bps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    complete_job: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    freelancer_fee_portion_bps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    freelancers: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {successful_jobs: bigint, total_jobs: bigint, ongoing: bigint, verified: boolean }],
      'view'
    >
    

    
    get_job: TypedContractMethod<
      [job_id: BytesLike, ],
      [JobPayingSystem.JobStructOutput],
      'view'
    >
    

    
    get_job_lists_len: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    get_level: TypedContractMethod<
      [index: BigNumberish, ],
      [JobPayingSystem.W_levelStructOutput],
      'view'
    >
    

    
    get_levels: TypedContractMethod<
      [],
      [JobPayingSystem.W_levelStructOutput[]],
      'view'
    >
    

    
    handle_request_payment: TypedContractMethod<
      [pay_link: boolean, words: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    hire: TypedContractMethod<
      [job_id: BytesLike, freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    isConsumingScheduledOp: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    job_lists: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    jobs: TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, boolean, boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {client: string, freelancer: string, freelancer_approved: boolean, freelancer_completed: boolean, appeal_time: bigint, status: bigint, amount: bigint, max_duration: bigint, expiry_timestamp: bigint, level: bigint, cat: bigint }],
      'view'
    >
    

    
    levels_size: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    pay_freelancer: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    post_job: TypedContractMethod<
      [job_id: BytesLike, amount: BigNumberish, max_duration: BigNumberish, category: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    raise_dispute: TypedContractMethod<
      [job_id: BytesLike, pay_link: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    refund_after_dispute: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    register_freelancer: TypedContractMethod<
      [freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reset_levels: TypedContractMethod<
      [_levels: JobPayingSystem.W_levelStruct[], ],
      [void],
      'nonpayable'
    >
    

    
    setAuthority: TypedContractMethod<
      [newAuthority: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_client_fee_portion: TypedContractMethod<
      [val: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transfer_freelancer: TypedContractMethod<
      [new_free: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    update_level: TypedContractMethod<
      [_level: JobPayingSystem.W_levelStruct, index: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    work_levels: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {min_verifiers_portion: bigint, freelancer_stake: bigint, client_stake: bigint, max_amount: bigint, payment_duration: bigint }],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'MIN_MAX_DURATION'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'STAKE_DECIMAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VERIFIERS_RECYCLING_PER_JOB'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'VERIFIER_DECIMAL'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'accept_job'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'append_level'): TypedContractMethod<
      [_level: JobPayingSystem.W_levelStruct, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'authority'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'cancel_hire'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancel_job'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancel_pending_hire'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claim_after_dispute'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'client_fee_portion_bps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'complete_job'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'freelancer_fee_portion_bps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'freelancers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint, bigint, boolean] & {successful_jobs: bigint, total_jobs: bigint, ongoing: bigint, verified: boolean }],
      'view'
    >;
getFunction(nameOrSignature: 'get_job'): TypedContractMethod<
      [job_id: BytesLike, ],
      [JobPayingSystem.JobStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'get_job_lists_len'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'get_level'): TypedContractMethod<
      [index: BigNumberish, ],
      [JobPayingSystem.W_levelStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'get_levels'): TypedContractMethod<
      [],
      [JobPayingSystem.W_levelStructOutput[]],
      'view'
    >;
getFunction(nameOrSignature: 'handle_request_payment'): TypedContractMethod<
      [pay_link: boolean, words: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'hire'): TypedContractMethod<
      [job_id: BytesLike, freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isConsumingScheduledOp'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'job_lists'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'jobs'): TypedContractMethod<
      [arg0: BytesLike, ],
      [[string, string, boolean, boolean, bigint, bigint, bigint, bigint, bigint, bigint, bigint] & {client: string, freelancer: string, freelancer_approved: boolean, freelancer_completed: boolean, appeal_time: bigint, status: bigint, amount: bigint, max_duration: bigint, expiry_timestamp: bigint, level: bigint, cat: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'levels_size'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'pay_freelancer'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'post_job'): TypedContractMethod<
      [job_id: BytesLike, amount: BigNumberish, max_duration: BigNumberish, category: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'raise_dispute'): TypedContractMethod<
      [job_id: BytesLike, pay_link: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'refund_after_dispute'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'register_freelancer'): TypedContractMethod<
      [freelancer: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reset_levels'): TypedContractMethod<
      [_levels: JobPayingSystem.W_levelStruct[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setAuthority'): TypedContractMethod<
      [newAuthority: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_client_fee_portion'): TypedContractMethod<
      [val: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transfer_freelancer'): TypedContractMethod<
      [new_free: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'update_level'): TypedContractMethod<
      [_level: JobPayingSystem.W_levelStruct, index: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'work_levels'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, bigint, bigint, bigint, bigint] & {min_verifiers_portion: bigint, freelancer_stake: bigint, client_stake: bigint, max_amount: bigint, payment_duration: bigint }],
      'view'
    >;

    getEvent(key: 'AuthorityUpdated'): TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
getEvent(key: 'job_accepted'): TypedContractEvent<job_acceptedEvent.InputTuple, job_acceptedEvent.OutputTuple, job_acceptedEvent.OutputObject>;
getEvent(key: 'job_closed'): TypedContractEvent<job_closedEvent.InputTuple, job_closedEvent.OutputTuple, job_closedEvent.OutputObject>;
getEvent(key: 'job_completed'): TypedContractEvent<job_completedEvent.InputTuple, job_completedEvent.OutputTuple, job_completedEvent.OutputObject>;
getEvent(key: 'job_disputed'): TypedContractEvent<job_disputedEvent.InputTuple, job_disputedEvent.OutputTuple, job_disputedEvent.OutputObject>;
getEvent(key: 'job_hired'): TypedContractEvent<job_hiredEvent.InputTuple, job_hiredEvent.OutputTuple, job_hiredEvent.OutputObject>;
getEvent(key: 'job_posted'): TypedContractEvent<job_postedEvent.InputTuple, job_postedEvent.OutputTuple, job_postedEvent.OutputObject>;
getEvent(key: 'transfer_address'): TypedContractEvent<transfer_addressEvent.InputTuple, transfer_addressEvent.OutputTuple, transfer_addressEvent.OutputObject>;

    filters: {
      
      'AuthorityUpdated(address)': TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
      AuthorityUpdated: TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
    

      'job_accepted(bytes32,address)': TypedContractEvent<job_acceptedEvent.InputTuple, job_acceptedEvent.OutputTuple, job_acceptedEvent.OutputObject>;
      job_accepted: TypedContractEvent<job_acceptedEvent.InputTuple, job_acceptedEvent.OutputTuple, job_acceptedEvent.OutputObject>;
    

      'job_closed(bytes32)': TypedContractEvent<job_closedEvent.InputTuple, job_closedEvent.OutputTuple, job_closedEvent.OutputObject>;
      job_closed: TypedContractEvent<job_closedEvent.InputTuple, job_closedEvent.OutputTuple, job_closedEvent.OutputObject>;
    

      'job_completed(bytes32,address)': TypedContractEvent<job_completedEvent.InputTuple, job_completedEvent.OutputTuple, job_completedEvent.OutputObject>;
      job_completed: TypedContractEvent<job_completedEvent.InputTuple, job_completedEvent.OutputTuple, job_completedEvent.OutputObject>;
    

      'job_disputed(bytes32,address,address,bool)': TypedContractEvent<job_disputedEvent.InputTuple, job_disputedEvent.OutputTuple, job_disputedEvent.OutputObject>;
      job_disputed: TypedContractEvent<job_disputedEvent.InputTuple, job_disputedEvent.OutputTuple, job_disputedEvent.OutputObject>;
    

      'job_hired(bytes32,address,address)': TypedContractEvent<job_hiredEvent.InputTuple, job_hiredEvent.OutputTuple, job_hiredEvent.OutputObject>;
      job_hired: TypedContractEvent<job_hiredEvent.InputTuple, job_hiredEvent.OutputTuple, job_hiredEvent.OutputObject>;
    

      'job_posted(bytes32)': TypedContractEvent<job_postedEvent.InputTuple, job_postedEvent.OutputTuple, job_postedEvent.OutputObject>;
      job_posted: TypedContractEvent<job_postedEvent.InputTuple, job_postedEvent.OutputTuple, job_postedEvent.OutputObject>;
    

      'transfer_address(address,address)': TypedContractEvent<transfer_addressEvent.InputTuple, transfer_addressEvent.OutputTuple, transfer_addressEvent.OutputObject>;
      transfer_address: TypedContractEvent<transfer_addressEvent.InputTuple, transfer_addressEvent.OutputTuple, transfer_addressEvent.OutputObject>;
    
    };
  }