/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVRFV2Wrapper, IVRFV2WrapperInterface } from "../../JobPayingSystem.sol/IVRFV2Wrapper.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "_callbackGasLimit",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "_numWords",
        "type": "uint32"
      }
    ],
    "name": "calculateRequestPrice",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "uint32",
        "name": "_callbackGasLimit",
        "type": "uint32"
      },
      {
        "internalType": "uint32",
        "name": "_numWords",
        "type": "uint32"
      }
    ],
    "name": "calculateRequestPriceNative",
    "outputs": [
      {
        "internalType": "uint256",
        "name": "",
        "type": "uint256"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IVRFV2Wrapper__factory {
    static readonly abi = _abi;
    static createInterface(): IVRFV2WrapperInterface {
      return new Interface(_abi) as IVRFV2WrapperInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVRFV2Wrapper {
      return new Contract(address, _abi, runner) as unknown as IVRFV2Wrapper;
    }
  }
  