/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as ethioCoinSol from './EthioCoin.sol/index.js';
export * as jobPayingSystemSol from './JobPayingSystem.sol/index.js';
export * as reputationTokenSol from './ReputationToken.sol/index.js';
export * as rewardVaultSol from './RewardVault.sol/index.js';
export * as treasureSol from './Treasure.sol/index.js';
export * as verifierSystemSol from './VerifierSystem.sol/index.js';