/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface TreasureInterface extends Interface {
    getFunction(nameOrSignature: "allocate_stable_coin" | "allocated_stable_coin" | "buy_back" | "deallocate_stable_coin" | "fill_reward_vault" | "get_balance_reputation_token" | "get_balance_stable_coin" | "locked_stable_coin" | "owner" | "renounceOwnership" | "reputation_token" | "reward_vault" | "set_reputation_token" | "set_reward_vault" | "set_uniswap_router" | "stable_coin" | "swap_reputation_for_stable" | "swap_stable_for_reputation" | "transferOwnership" | "transfer_allocated_stable_coin" | "uniswap_router" | "withdraw_tokens"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'allocate_stable_coin', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'allocated_stable_coin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'buy_back', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'deallocate_stable_coin', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'fill_reward_vault', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'get_balance_reputation_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_balance_stable_coin', values?: undefined): string;
encodeFunctionData(functionFragment: 'locked_stable_coin', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'reputation_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'reward_vault', values?: undefined): string;
encodeFunctionData(functionFragment: 'set_reputation_token', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_reward_vault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_uniswap_router', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'stable_coin', values?: undefined): string;
encodeFunctionData(functionFragment: 'swap_reputation_for_stable', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'swap_stable_for_reputation', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'transfer_allocated_stable_coin', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'uniswap_router', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw_tokens', values: [AddressLike, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'allocate_stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allocated_stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'buy_back', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deallocate_stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'fill_reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_balance_reputation_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_balance_stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'locked_stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputation_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_reputation_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_uniswap_router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap_reputation_for_stable', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'swap_stable_for_reputation', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transfer_allocated_stable_coin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'uniswap_router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw_tokens', data: BytesLike): Result;
  }

  
    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Treasure extends BaseContract {
    
    connect(runner?: ContractRunner | null): Treasure;
    waitForDeployment(): Promise<this>;

    interface: TreasureInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    allocate_stable_coin: TypedContractMethod<
      [beneficiary: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    allocated_stable_coin: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    buy_back: TypedContractMethod<
      [amount: BigNumberish, liquidator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    deallocate_stable_coin: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    fill_reward_vault: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    get_balance_reputation_token: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    get_balance_stable_coin: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    locked_stable_coin: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    reputation_token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reward_vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    set_reputation_token: TypedContractMethod<
      [reputation_token_address: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_reward_vault: TypedContractMethod<
      [new_reward_vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_uniswap_router: TypedContractMethod<
      [_uniswap_router: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    stable_coin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    swap_reputation_for_stable: TypedContractMethod<
      [reputation_amount: BigNumberish, min_stable_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    swap_stable_for_reputation: TypedContractMethod<
      [stable_amount: BigNumberish, min_reputation_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    transfer_allocated_stable_coin: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    uniswap_router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    withdraw_tokens: TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'allocate_stable_coin'): TypedContractMethod<
      [beneficiary: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'allocated_stable_coin'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'buy_back'): TypedContractMethod<
      [amount: BigNumberish, liquidator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deallocate_stable_coin'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'fill_reward_vault'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'get_balance_reputation_token'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'get_balance_stable_coin'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'locked_stable_coin'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputation_token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reward_vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'set_reputation_token'): TypedContractMethod<
      [reputation_token_address: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_reward_vault'): TypedContractMethod<
      [new_reward_vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_uniswap_router'): TypedContractMethod<
      [_uniswap_router: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stable_coin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'swap_reputation_for_stable'): TypedContractMethod<
      [reputation_amount: BigNumberish, min_stable_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'swap_stable_for_reputation'): TypedContractMethod<
      [stable_amount: BigNumberish, min_reputation_amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transfer_allocated_stable_coin'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'uniswap_router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw_tokens'): TypedContractMethod<
      [to: AddressLike, amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;

    filters: {
      
      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    
    };
  }