/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { IRegistry__factory } from './IRegistry__factory.js';
export { Registry__factory } from './Registry__factory.js';