/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RewardVaultInterface extends Interface {
    getFunction(nameOrSignature: "acc_reward_per_share" | "last_reward_time" | "lptoken" | "reward_rate" | "reward_token" | "stake" | "total_staked" | "user_infos" | "withdraw"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'acc_reward_per_share', values?: undefined): string;
encodeFunctionData(functionFragment: 'last_reward_time', values?: undefined): string;
encodeFunctionData(functionFragment: 'lptoken', values?: undefined): string;
encodeFunctionData(functionFragment: 'reward_rate', values?: undefined): string;
encodeFunctionData(functionFragment: 'reward_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'total_staked', values?: undefined): string;
encodeFunctionData(functionFragment: 'user_infos', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acc_reward_per_share', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'last_reward_time', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lptoken', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reward_rate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reward_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'total_staked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'user_infos', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  

  export interface RewardVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): RewardVault;
    waitForDeployment(): Promise<this>;

    interface: RewardVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acc_reward_per_share: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    last_reward_time: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    lptoken: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reward_rate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    reward_token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    total_staked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    user_infos: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint] & {amount: bigint, reward_debt: bigint }],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acc_reward_per_share'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'last_reward_time'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'lptoken'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reward_rate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'reward_token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'total_staked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'user_infos'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint] & {amount: bigint, reward_debt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    

    filters: {
      
    };
  }