/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface VerifierSystemInterface extends Interface {
    getFunction(nameOrSignature: "WEIGHT_MAX" | "acceptOwnership" | "add_verifier" | "callback_gas_limit" | "category_not_open" | "claim_rewards" | "finalize_verification" | "inactive_verifier" | "key_hash" | "owner" | "pending_rewards" | "rawFulfillRandomWords" | "reputation_token" | "request_confirmations" | "request_random_nums" | "reveal_decision" | "s_vrfCoordinator" | "setCoordinator" | "set_slash_bps" | "set_treasury" | "slash_bps" | "stake" | "submit_hashed_decision" | "subscription_id" | "transferOwnership" | "treasury_address" | "treasury_pending" | "verifier_requests" | "verifiers" | "verifiers_in_category" | "withdraw_treasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "CoordinatorSet" | "OwnershipTransferRequested" | "OwnershipTransferred" | "decision_revealed" | "hashed_decision_submitted" | "job_finalized" | "job_initialized" | "request_fulfilled(uint256,uint256[],bytes32)" | "request_fulfilled(uint256,uint256[])" | "request_sent" | "reward_credited" | "rewards_claimed" | "treasury_set" | "verifier_added" | "verifier_slashed" | "verifier_staked" | "verifier_unstaked"): EventFragment;

    encodeFunctionData(functionFragment: 'WEIGHT_MAX', values?: undefined): string;
encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'add_verifier', values: [BigNumberish, AddressLike]): string;
encodeFunctionData(functionFragment: 'callback_gas_limit', values?: undefined): string;
encodeFunctionData(functionFragment: 'category_not_open', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'claim_rewards', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalize_verification', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'inactive_verifier', values?: undefined): string;
encodeFunctionData(functionFragment: 'key_hash', values?: undefined): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pending_rewards', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'rawFulfillRandomWords', values: [BigNumberish, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'reputation_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'request_confirmations', values?: undefined): string;
encodeFunctionData(functionFragment: 'request_random_nums', values: [boolean, BytesLike]): string;
encodeFunctionData(functionFragment: 'reveal_decision', values: [BytesLike, BytesLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 's_vrfCoordinator', values?: undefined): string;
encodeFunctionData(functionFragment: 'setCoordinator', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_slash_bps', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'set_treasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'slash_bps', values?: undefined): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'submit_hashed_decision', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'subscription_id', values?: undefined): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury_address', values?: undefined): string;
encodeFunctionData(functionFragment: 'treasury_pending', values?: undefined): string;
encodeFunctionData(functionFragment: 'verifier_requests', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'verifiers', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'verifiers_in_category', values: [BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw_treasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'WEIGHT_MAX', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'add_verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'callback_gas_limit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'category_not_open', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claim_rewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalize_verification', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'inactive_verifier', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'key_hash', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pending_rewards', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rawFulfillRandomWords', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reputation_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'request_confirmations', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'request_random_nums', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reveal_decision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 's_vrfCoordinator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setCoordinator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_slash_bps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'slash_bps', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'submit_hashed_decision', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'subscription_id', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury_address', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury_pending', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifier_requests', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiers', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'verifiers_in_category', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw_treasury', data: BytesLike): Result;
  }

  
    export namespace CoordinatorSetEvent {
      export type InputTuple = [vrfCoordinator: AddressLike];
      export type OutputTuple = [vrfCoordinator: string];
      export interface OutputObject {vrfCoordinator: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferRequestedEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike];
      export type OutputTuple = [from: string, to: string];
      export interface OutputObject {from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [from: AddressLike, to: AddressLike];
      export type OutputTuple = [from: string, to: string];
      export interface OutputObject {from: string, to: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace decision_revealedEvent {
      export type InputTuple = [job_id: BytesLike, verifier: AddressLike, score: BigNumberish];
      export type OutputTuple = [job_id: string, verifier: string, score: bigint];
      export interface OutputObject {job_id: string, verifier: string, score: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace hashed_decision_submittedEvent {
      export type InputTuple = [job_id: BytesLike, verifier: AddressLike];
      export type OutputTuple = [job_id: string, verifier: string];
      export interface OutputObject {job_id: string, verifier: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_finalizedEvent {
      export type InputTuple = [job_id: BytesLike, dispute_status: BigNumberish];
      export type OutputTuple = [job_id: string, dispute_status: bigint];
      export interface OutputObject {job_id: string, dispute_status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace job_initializedEvent {
      export type InputTuple = [job_id: BytesLike, category: BigNumberish, lock_amount: BigNumberish, min_verifiers: BigNumberish];
      export type OutputTuple = [job_id: string, category: bigint, lock_amount: bigint, min_verifiers: bigint];
      export interface OutputObject {job_id: string, category: bigint, lock_amount: bigint, min_verifiers: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace request_fulfilled_uint256_uint256_array_bytes32_Event {
      export type InputTuple = [request_id: BigNumberish, random_values: BigNumberish[], job_id: BytesLike];
      export type OutputTuple = [request_id: bigint, random_values: bigint[], job_id: string];
      export interface OutputObject {request_id: bigint, random_values: bigint[], job_id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace request_fulfilled_uint256_uint256_array_Event {
      export type InputTuple = [request_id: BigNumberish, random_words: BigNumberish[]];
      export type OutputTuple = [request_id: bigint, random_words: bigint[]];
      export interface OutputObject {request_id: bigint, random_words: bigint[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace request_sentEvent {
      export type InputTuple = [request_id: BigNumberish, num_words: BigNumberish, job_id: BytesLike];
      export type OutputTuple = [request_id: bigint, num_words: bigint, job_id: string];
      export interface OutputObject {request_id: bigint, num_words: bigint, job_id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace reward_creditedEvent {
      export type InputTuple = [to: AddressLike, amount: BigNumberish];
      export type OutputTuple = [to: string, amount: bigint];
      export interface OutputObject {to: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace rewards_claimedEvent {
      export type InputTuple = [by: AddressLike, amount: BigNumberish];
      export type OutputTuple = [by: string, amount: bigint];
      export interface OutputObject {by: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace treasury_setEvent {
      export type InputTuple = [treasury: AddressLike];
      export type OutputTuple = [treasury: string];
      export interface OutputObject {treasury: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace verifier_addedEvent {
      export type InputTuple = [verifier: AddressLike, category: BigNumberish];
      export type OutputTuple = [verifier: string, category: bigint];
      export interface OutputObject {verifier: string, category: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace verifier_slashedEvent {
      export type InputTuple = [verifier: AddressLike, amount: BigNumberish, job_id: BytesLike];
      export type OutputTuple = [verifier: string, amount: bigint, job_id: string];
      export interface OutputObject {verifier: string, amount: bigint, job_id: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace verifier_stakedEvent {
      export type InputTuple = [verifier: AddressLike, amount: BigNumberish];
      export type OutputTuple = [verifier: string, amount: bigint];
      export interface OutputObject {verifier: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace verifier_unstakedEvent {
      export type InputTuple = [verifier: AddressLike, amount: BigNumberish];
      export type OutputTuple = [verifier: string, amount: bigint];
      export interface OutputObject {verifier: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface VerifierSystem extends BaseContract {
    
    connect(runner?: ContractRunner | null): VerifierSystem;
    waitForDeployment(): Promise<this>;

    interface: VerifierSystemInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    WEIGHT_MAX: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    add_verifier: TypedContractMethod<
      [category: BigNumberish, verifier: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    callback_gas_limit: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    category_not_open: TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    claim_rewards: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    finalize_verification: TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    inactive_verifier: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    key_hash: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pending_rewards: TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    rawFulfillRandomWords: TypedContractMethod<
      [requestId: BigNumberish, randomWords: BigNumberish[], ],
      [void],
      'nonpayable'
    >
    

    
    reputation_token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    request_confirmations: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    request_random_nums: TypedContractMethod<
      [enable_native_payment: boolean, job_id: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    reveal_decision: TypedContractMethod<
      [job_id: BytesLike, salt: BytesLike, decision: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    s_vrfCoordinator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setCoordinator: TypedContractMethod<
      [_vrfCoordinator: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_slash_bps: TypedContractMethod<
      [_bps: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    set_treasury: TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    slash_bps: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    submit_hashed_decision: TypedContractMethod<
      [job_id: BytesLike, hashed_decision: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    subscription_id: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    transferOwnership: TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury_address: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    treasury_pending: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    verifier_requests: TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >
    

    
    verifiers: TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, boolean, bigint, bigint, bigint, bigint] & {verified: boolean, is_active: boolean, in_dispute: bigint, locked: bigint, staked: bigint, category: bigint }],
      'view'
    >
    

    
    verifiers_in_category: TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >
    

    
    withdraw_treasury: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'WEIGHT_MAX'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'add_verifier'): TypedContractMethod<
      [category: BigNumberish, verifier: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'callback_gas_limit'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'category_not_open'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'claim_rewards'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'finalize_verification'): TypedContractMethod<
      [job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'inactive_verifier'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'key_hash'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pending_rewards'): TypedContractMethod<
      [arg0: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'rawFulfillRandomWords'): TypedContractMethod<
      [requestId: BigNumberish, randomWords: BigNumberish[], ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reputation_token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'request_confirmations'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'request_random_nums'): TypedContractMethod<
      [enable_native_payment: boolean, job_id: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'reveal_decision'): TypedContractMethod<
      [job_id: BytesLike, salt: BytesLike, decision: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 's_vrfCoordinator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setCoordinator'): TypedContractMethod<
      [_vrfCoordinator: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_slash_bps'): TypedContractMethod<
      [_bps: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_treasury'): TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'slash_bps'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'submit_hashed_decision'): TypedContractMethod<
      [job_id: BytesLike, hashed_decision: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'subscription_id'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [to: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury_address'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'treasury_pending'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'verifier_requests'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'verifiers'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[boolean, boolean, bigint, bigint, bigint, bigint] & {verified: boolean, is_active: boolean, in_dispute: bigint, locked: bigint, staked: bigint, category: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'verifiers_in_category'): TypedContractMethod<
      [arg0: BigNumberish, arg1: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw_treasury'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'CoordinatorSet'): TypedContractEvent<CoordinatorSetEvent.InputTuple, CoordinatorSetEvent.OutputTuple, CoordinatorSetEvent.OutputObject>;
getEvent(key: 'OwnershipTransferRequested'): TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'decision_revealed'): TypedContractEvent<decision_revealedEvent.InputTuple, decision_revealedEvent.OutputTuple, decision_revealedEvent.OutputObject>;
getEvent(key: 'hashed_decision_submitted'): TypedContractEvent<hashed_decision_submittedEvent.InputTuple, hashed_decision_submittedEvent.OutputTuple, hashed_decision_submittedEvent.OutputObject>;
getEvent(key: 'job_finalized'): TypedContractEvent<job_finalizedEvent.InputTuple, job_finalizedEvent.OutputTuple, job_finalizedEvent.OutputObject>;
getEvent(key: 'job_initialized'): TypedContractEvent<job_initializedEvent.InputTuple, job_initializedEvent.OutputTuple, job_initializedEvent.OutputObject>;
getEvent(key: 'request_fulfilled(uint256,uint256[],bytes32)'): TypedContractEvent<request_fulfilled_uint256_uint256_array_bytes32_Event.InputTuple, request_fulfilled_uint256_uint256_array_bytes32_Event.OutputTuple, request_fulfilled_uint256_uint256_array_bytes32_Event.OutputObject>;
getEvent(key: 'request_fulfilled(uint256,uint256[])'): TypedContractEvent<request_fulfilled_uint256_uint256_array_Event.InputTuple, request_fulfilled_uint256_uint256_array_Event.OutputTuple, request_fulfilled_uint256_uint256_array_Event.OutputObject>;
getEvent(key: 'request_sent'): TypedContractEvent<request_sentEvent.InputTuple, request_sentEvent.OutputTuple, request_sentEvent.OutputObject>;
getEvent(key: 'reward_credited'): TypedContractEvent<reward_creditedEvent.InputTuple, reward_creditedEvent.OutputTuple, reward_creditedEvent.OutputObject>;
getEvent(key: 'rewards_claimed'): TypedContractEvent<rewards_claimedEvent.InputTuple, rewards_claimedEvent.OutputTuple, rewards_claimedEvent.OutputObject>;
getEvent(key: 'treasury_set'): TypedContractEvent<treasury_setEvent.InputTuple, treasury_setEvent.OutputTuple, treasury_setEvent.OutputObject>;
getEvent(key: 'verifier_added'): TypedContractEvent<verifier_addedEvent.InputTuple, verifier_addedEvent.OutputTuple, verifier_addedEvent.OutputObject>;
getEvent(key: 'verifier_slashed'): TypedContractEvent<verifier_slashedEvent.InputTuple, verifier_slashedEvent.OutputTuple, verifier_slashedEvent.OutputObject>;
getEvent(key: 'verifier_staked'): TypedContractEvent<verifier_stakedEvent.InputTuple, verifier_stakedEvent.OutputTuple, verifier_stakedEvent.OutputObject>;
getEvent(key: 'verifier_unstaked'): TypedContractEvent<verifier_unstakedEvent.InputTuple, verifier_unstakedEvent.OutputTuple, verifier_unstakedEvent.OutputObject>;

    filters: {
      
      'CoordinatorSet(address)': TypedContractEvent<CoordinatorSetEvent.InputTuple, CoordinatorSetEvent.OutputTuple, CoordinatorSetEvent.OutputObject>;
      CoordinatorSet: TypedContractEvent<CoordinatorSetEvent.InputTuple, CoordinatorSetEvent.OutputTuple, CoordinatorSetEvent.OutputObject>;
    

      'OwnershipTransferRequested(address,address)': TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
      OwnershipTransferRequested: TypedContractEvent<OwnershipTransferRequestedEvent.InputTuple, OwnershipTransferRequestedEvent.OutputTuple, OwnershipTransferRequestedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'decision_revealed(bytes32,address,uint256)': TypedContractEvent<decision_revealedEvent.InputTuple, decision_revealedEvent.OutputTuple, decision_revealedEvent.OutputObject>;
      decision_revealed: TypedContractEvent<decision_revealedEvent.InputTuple, decision_revealedEvent.OutputTuple, decision_revealedEvent.OutputObject>;
    

      'hashed_decision_submitted(bytes32,address)': TypedContractEvent<hashed_decision_submittedEvent.InputTuple, hashed_decision_submittedEvent.OutputTuple, hashed_decision_submittedEvent.OutputObject>;
      hashed_decision_submitted: TypedContractEvent<hashed_decision_submittedEvent.InputTuple, hashed_decision_submittedEvent.OutputTuple, hashed_decision_submittedEvent.OutputObject>;
    

      'job_finalized(bytes32,uint8)': TypedContractEvent<job_finalizedEvent.InputTuple, job_finalizedEvent.OutputTuple, job_finalizedEvent.OutputObject>;
      job_finalized: TypedContractEvent<job_finalizedEvent.InputTuple, job_finalizedEvent.OutputTuple, job_finalizedEvent.OutputObject>;
    

      'job_initialized(bytes32,uint8,uint256,uint256)': TypedContractEvent<job_initializedEvent.InputTuple, job_initializedEvent.OutputTuple, job_initializedEvent.OutputObject>;
      job_initialized: TypedContractEvent<job_initializedEvent.InputTuple, job_initializedEvent.OutputTuple, job_initializedEvent.OutputObject>;
    
'request_fulfilled(uint256,uint256[],bytes32)': TypedContractEvent<request_fulfilled_uint256_uint256_array_bytes32_Event.InputTuple, request_fulfilled_uint256_uint256_array_bytes32_Event.OutputTuple, request_fulfilled_uint256_uint256_array_bytes32_Event.OutputObject>;
'request_fulfilled(uint256,uint256[])': TypedContractEvent<request_fulfilled_uint256_uint256_array_Event.InputTuple, request_fulfilled_uint256_uint256_array_Event.OutputTuple, request_fulfilled_uint256_uint256_array_Event.OutputObject>;

      'request_sent(uint256,uint256,bytes32)': TypedContractEvent<request_sentEvent.InputTuple, request_sentEvent.OutputTuple, request_sentEvent.OutputObject>;
      request_sent: TypedContractEvent<request_sentEvent.InputTuple, request_sentEvent.OutputTuple, request_sentEvent.OutputObject>;
    

      'reward_credited(address,uint256)': TypedContractEvent<reward_creditedEvent.InputTuple, reward_creditedEvent.OutputTuple, reward_creditedEvent.OutputObject>;
      reward_credited: TypedContractEvent<reward_creditedEvent.InputTuple, reward_creditedEvent.OutputTuple, reward_creditedEvent.OutputObject>;
    

      'rewards_claimed(address,uint256)': TypedContractEvent<rewards_claimedEvent.InputTuple, rewards_claimedEvent.OutputTuple, rewards_claimedEvent.OutputObject>;
      rewards_claimed: TypedContractEvent<rewards_claimedEvent.InputTuple, rewards_claimedEvent.OutputTuple, rewards_claimedEvent.OutputObject>;
    

      'treasury_set(address)': TypedContractEvent<treasury_setEvent.InputTuple, treasury_setEvent.OutputTuple, treasury_setEvent.OutputObject>;
      treasury_set: TypedContractEvent<treasury_setEvent.InputTuple, treasury_setEvent.OutputTuple, treasury_setEvent.OutputObject>;
    

      'verifier_added(address,uint8)': TypedContractEvent<verifier_addedEvent.InputTuple, verifier_addedEvent.OutputTuple, verifier_addedEvent.OutputObject>;
      verifier_added: TypedContractEvent<verifier_addedEvent.InputTuple, verifier_addedEvent.OutputTuple, verifier_addedEvent.OutputObject>;
    

      'verifier_slashed(address,uint256,bytes32)': TypedContractEvent<verifier_slashedEvent.InputTuple, verifier_slashedEvent.OutputTuple, verifier_slashedEvent.OutputObject>;
      verifier_slashed: TypedContractEvent<verifier_slashedEvent.InputTuple, verifier_slashedEvent.OutputTuple, verifier_slashedEvent.OutputObject>;
    

      'verifier_staked(address,uint256)': TypedContractEvent<verifier_stakedEvent.InputTuple, verifier_stakedEvent.OutputTuple, verifier_stakedEvent.OutputObject>;
      verifier_staked: TypedContractEvent<verifier_stakedEvent.InputTuple, verifier_stakedEvent.OutputTuple, verifier_stakedEvent.OutputObject>;
    

      'verifier_unstaked(address,uint256)': TypedContractEvent<verifier_unstakedEvent.InputTuple, verifier_unstakedEvent.OutputTuple, verifier_unstakedEvent.OutputObject>;
      verifier_unstaked: TypedContractEvent<verifier_unstakedEvent.InputTuple, verifier_unstakedEvent.OutputTuple, verifier_unstakedEvent.OutputObject>;
    
    };
  }