[profile.default]
src = "contracts"
test = "test"
libs = ["lib"]
out = "out"

remappings = [
  "@chainlink/=lib/chainlink-evm/",
  "@openzeppelin/=lib/openzeppelin-contracts/",
  "@uniswap/=lib/",
  "forge-std/=lib/forge-std/"
]