/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface IRegistryInterface extends Interface {
    getFunction(nameOrSignature: "get_ethiocoin" | "get_factory" | "get_job_manager" | "get_lp_token" | "get_pool" | "get_reward_vault" | "get_router" | "get_rpt" | "get_treasury" | "get_verifier"): FunctionFragment;

    

    encodeFunctionData(functionFragment: 'get_ethiocoin', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_factory', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_job_manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_lp_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_pool', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_reward_vault', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_router', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_rpt', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_verifier', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'get_ethiocoin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_factory', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_job_manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_lp_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_pool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_router', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_rpt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_verifier', data: BytesLike): Result;
  }

  

  export interface IRegistry extends BaseContract {
    
    connect(runner?: ContractRunner | null): IRegistry;
    waitForDeployment(): Promise<this>;

    interface: IRegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    get_ethiocoin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_factory: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_job_manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_lp_token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_pool: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_reward_vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_router: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_rpt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_verifier: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'get_ethiocoin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_factory'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_job_manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_lp_token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_pool'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_reward_vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_router'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_rpt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_verifier'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    

    filters: {
      
    };
  }