/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { Itreasury, ItreasuryInterface } from "../../VerifierSystem.sol/Itreasury";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "pay_back_rpt",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "address",
        "name": "to",
        "type": "address"
      },
      {
        "internalType": "uint256",
        "name": "amount",
        "type": "uint256"
      }
    ],
    "name": "pay_back_stable_coin",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class Itreasury__factory {
    static readonly abi = _abi;
    static createInterface(): ItreasuryInterface {
      return new Interface(_abi) as ItreasuryInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): Itreasury {
      return new Contract(address, _abi, runner) as unknown as Itreasury;
    }
  }
  