/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IVerifierSystem, IVerifierSystemInterface } from "../../VerifierSystem.sol/IVerifierSystem.js";

  const _abi = [
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "job_id",
        "type": "bytes32"
      }
    ],
    "name": "get_dispute_status",
    "outputs": [
      {
        "internalType": "enum IVerifierSystem.DISPUTE_STATUS",
        "name": "",
        "type": "uint8"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [],
    "name": "get_request_config",
    "outputs": [
      {
        "internalType": "uint32",
        "name": "",
        "type": "uint32"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      },
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bytes32",
        "name": "job_id",
        "type": "bytes32"
      },
      {
        "internalType": "uint8",
        "name": "cat",
        "type": "uint8"
      },
      {
        "internalType": "uint256",
        "name": "client_stake",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "freelancer_stake",
        "type": "uint256"
      }
    ],
    "name": "post_job",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "inputs": [
      {
        "internalType": "bool",
        "name": "enable_native_payment",
        "type": "bool"
      },
      {
        "internalType": "bytes32",
        "name": "job_id",
        "type": "bytes32"
      },
      {
        "internalType": "uint256",
        "name": "stake_amount",
        "type": "uint256"
      },
      {
        "internalType": "uint256",
        "name": "verifiers_cnt",
        "type": "uint256"
      }
    ],
    "name": "request_random_nums",
    "outputs": [],
    "stateMutability": "nonpayable",
    "type": "function"
  }
] as const;

  export class IVerifierSystem__factory {
    static readonly abi = _abi;
    static createInterface(): IVerifierSystemInterface {
      return new Interface(_abi) as IVerifierSystemInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IVerifierSystem {
      return new Contract(address, _abi, runner) as unknown as IVerifierSystem;
    }
  }
  