/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RewardVaultInterface extends Interface {
    getFunction(nameOrSignature: "acc_reward_per_share" | "authority" | "isConsumingScheduledOp" | "last_reward_time" | "liqudators" | "registry" | "reward_rate" | "setAuthority" | "set_reward_rate" | "stake" | "total_staked" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'acc_reward_per_share', values?: undefined): string;
encodeFunctionData(functionFragment: 'authority', values?: undefined): string;
encodeFunctionData(functionFragment: 'isConsumingScheduledOp', values?: undefined): string;
encodeFunctionData(functionFragment: 'last_reward_time', values?: undefined): string;
encodeFunctionData(functionFragment: 'liqudators', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'registry', values?: undefined): string;
encodeFunctionData(functionFragment: 'reward_rate', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuthority', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_reward_rate', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'stake', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'total_staked', values?: undefined): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acc_reward_per_share', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isConsumingScheduledOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'last_reward_time', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'liqudators', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'registry', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reward_rate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_reward_rate', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'stake', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'total_staked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace AuthorityUpdatedEvent {
      export type InputTuple = [authority: AddressLike];
      export type OutputTuple = [authority: string];
      export interface OutputObject {authority: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface RewardVault extends BaseContract {
    
    connect(runner?: ContractRunner | null): RewardVault;
    waitForDeployment(): Promise<this>;

    interface: RewardVaultInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acc_reward_per_share: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    authority: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isConsumingScheduledOp: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    last_reward_time: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    liqudators: TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint] & {amount: bigint, reward_debt: bigint }],
      'view'
    >
    

    
    registry: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reward_rate: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    setAuthority: TypedContractMethod<
      [newAuthority: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_reward_rate: TypedContractMethod<
      [_reward_rate: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    stake: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    total_staked: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acc_reward_per_share'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'authority'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isConsumingScheduledOp'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'last_reward_time'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'liqudators'): TypedContractMethod<
      [arg0: AddressLike, ],
      [[bigint, bigint] & {amount: bigint, reward_debt: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'registry'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reward_rate'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'setAuthority'): TypedContractMethod<
      [newAuthority: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_reward_rate'): TypedContractMethod<
      [_reward_rate: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'stake'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'total_staked'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'AuthorityUpdated'): TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;

    filters: {
      
      'AuthorityUpdated(address)': TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
      AuthorityUpdated: TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
    
    };
  }