/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  

  export interface RegistryInterface extends Interface {
    getFunction(nameOrSignature: "access_manager" | "authority" | "ethiocoin" | "get_access_manager" | "get_ethiocoin" | "get_job_manager" | "get_lp_token" | "get_reward_vault" | "get_rpt" | "get_treasury" | "isConsumingScheduledOp" | "job_manager" | "lp_token" | "reward_vault" | "rpt" | "setAuthority" | "set_ethiocoin" | "set_job_manager" | "set_lp_token" | "set_reward_vault" | "set_rpt" | "set_treasury" | "treasury"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "AuthorityUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'access_manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'authority', values?: undefined): string;
encodeFunctionData(functionFragment: 'ethiocoin', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_access_manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_ethiocoin', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_job_manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_lp_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_reward_vault', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_rpt', values?: undefined): string;
encodeFunctionData(functionFragment: 'get_treasury', values?: undefined): string;
encodeFunctionData(functionFragment: 'isConsumingScheduledOp', values?: undefined): string;
encodeFunctionData(functionFragment: 'job_manager', values?: undefined): string;
encodeFunctionData(functionFragment: 'lp_token', values?: undefined): string;
encodeFunctionData(functionFragment: 'reward_vault', values?: undefined): string;
encodeFunctionData(functionFragment: 'rpt', values?: undefined): string;
encodeFunctionData(functionFragment: 'setAuthority', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_ethiocoin', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_job_manager', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_lp_token', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_reward_vault', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_rpt', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'set_treasury', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'treasury', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'access_manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'authority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'ethiocoin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_access_manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_ethiocoin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_job_manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_lp_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_rpt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'get_treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isConsumingScheduledOp', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'job_manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'lp_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'rpt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setAuthority', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_ethiocoin', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_job_manager', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_lp_token', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_reward_vault', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_rpt', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'set_treasury', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'treasury', data: BytesLike): Result;
  }

  
    export namespace AuthorityUpdatedEvent {
      export type InputTuple = [authority: AddressLike];
      export type OutputTuple = [authority: string];
      export interface OutputObject {authority: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface Registry extends BaseContract {
    
    connect(runner?: ContractRunner | null): Registry;
    waitForDeployment(): Promise<this>;

    interface: RegistryInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    access_manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    authority: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    ethiocoin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_access_manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_ethiocoin: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_job_manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_lp_token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_reward_vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_rpt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    get_treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    isConsumingScheduledOp: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    job_manager: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    lp_token: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    reward_vault: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    rpt: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    setAuthority: TypedContractMethod<
      [newAuthority: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_ethiocoin: TypedContractMethod<
      [_ethiocoin: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_job_manager: TypedContractMethod<
      [_job_manager: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_lp_token: TypedContractMethod<
      [_lp_token: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_reward_vault: TypedContractMethod<
      [_reward_vault: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_rpt: TypedContractMethod<
      [_rpt: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    set_treasury: TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    treasury: TypedContractMethod<
      [],
      [string],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'access_manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'authority'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'ethiocoin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_access_manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_ethiocoin'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_job_manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_lp_token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_reward_vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_rpt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'get_treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'isConsumingScheduledOp'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'job_manager'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'lp_token'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'reward_vault'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'rpt'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'setAuthority'): TypedContractMethod<
      [newAuthority: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_ethiocoin'): TypedContractMethod<
      [_ethiocoin: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_job_manager'): TypedContractMethod<
      [_job_manager: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_lp_token'): TypedContractMethod<
      [_lp_token: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_reward_vault'): TypedContractMethod<
      [_reward_vault: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_rpt'): TypedContractMethod<
      [_rpt: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'set_treasury'): TypedContractMethod<
      [_treasury: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'treasury'): TypedContractMethod<
      [],
      [string],
      'view'
    >;

    getEvent(key: 'AuthorityUpdated'): TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;

    filters: {
      
      'AuthorityUpdated(address)': TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
      AuthorityUpdated: TypedContractEvent<AuthorityUpdatedEvent.InputTuple, AuthorityUpdatedEvent.OutputTuple, AuthorityUpdatedEvent.OutputObject>;
    
    };
  }